spring:
  application:
    name: admin-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        tags: version=1.0,author=fanxuankai
        healthCheckInterval: 5s
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        service-name: ${spring.application.name}
server:
  port: 8080
