spring:
  datasource:
    url: jdbc:mysql://localhost:3306/canal_client_example?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: HzB!OPxxE$5CwJIZ
    driver-class-name: com.mysql.cj.jdbc.Driver